## Yassin's hugo web page
## -- 
## configuration file

baseURL = 'https://yassinachengli.org'
languageCode = 'es'
title = "Yassin Achengli"
theme = 'book'

enableGitInfo = true
disablePathToLower = true

# book theme configuration
[params]
  BookTheme = 'light'
  BookToC = true
  BookLogo = '/logo.jpg'
  BookSection = '*'
  BookRepo = 'https://github.com/alex-shpak/hugo-book'
  BookCommitPath = 'commit'
  BookSearch = true
  BookComments = true
  BookPortableLinks = true
  BookServiceWorker = true

  bookHidden = false
  bookHref = ''
  type = 'docs'
  bookSearchExclude = true
  date_format = "03 Jan 2025"

[markup.tableOfContents]
  startLevel = 1

[languages]
[languages.es]
  languageName = 'Spanish'
  contentDir = 'content.es'
  weight = 1

[menu]
  [[menu.after]]
    name = 'Github'
    url = 'https://github.com/achengli'
    weight= 10

[[menu.after]]
  name = 'Yassin Achengli'
  url = 'http://yassinachengli.org'
  weight = 20

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[frontmatter]
  lastmod = [':it', ':fileModTime']

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['\(', '\)']]
